#!/usr/bin/env python3
"""Guard against hardcoded calendar-date literals in tests/.

Why this exists
---------------
On 2026-05-21/22 every PR going through CI failed on the same assertion in
`tests/unit/test_claude_code_intel_rollup.py::test_build_rolling_assets_writes_current_artifacts_and_repo_library`.
The fixture had hardcoded a packet date of "2026-04-23", which on that day
fell outside the 28-day rolling window (`UA_CLAUDE_CODE_INTEL_BRIEF_WINDOW_DAYS=28`),
so `bundle_count` collapsed to 0. Fixed in commit e717c273 by switching to
`now() - timedelta(days=7)`.

To prevent the next time-bomb, this script flags any *new* quoted YYYY-MM-DD
literal under `tests/`. Existing literals are grandfathered via a baseline
file so this PR doesn't have to touch 71 unrelated test lines.

How to use
----------
Run from repo root:

    python scripts/check_test_date_literals.py

Exits 0 if clean, 1 if there are new violations.

Resolution options when CI flags a line:
1. Prefer: replace the literal with a relative date, e.g.
       (date.today() - timedelta(days=7)).isoformat()
2. If the date really must be pinned, annotate the line:
       run_date = "2026-04-23"  # date-pinned-ok
3. Refresh the baseline (only when grandfathering something you cannot fix now):
       python scripts/check_test_date_literals.py --update-baseline
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = REPO_ROOT / "tests"
BASELINE = Path(__file__).resolve().parent / "test_date_literal_baseline.txt"
OPT_OUT_MARKER = "# date-pinned-ok"

# Matches a YYYY-MM-DD inside single or double quotes. Year band 1900-2099
# keeps this from matching things like version strings ("2.0.1-rc2").
DATE_LITERAL_RE = re.compile(r"""["'](?:19|20)\d{2}-\d{2}-\d{2}["']""")


def iter_test_files() -> list[Path]:
    return sorted(p for p in TESTS_DIR.rglob("*.py") if p.is_file())


def scan(files: list[Path]) -> list[tuple[Path, int, str]]:
    hits: list[tuple[Path, int, str]] = []
    for path in files:
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if not DATE_LITERAL_RE.search(line):
                continue
            if OPT_OUT_MARKER in line:
                continue
            hits.append((path, lineno, line.strip()))
    return hits


def load_baseline() -> set[tuple[str, str]]:
    if not BASELINE.exists():
        return set()
    keys: set[tuple[str, str]] = set()
    for raw in BASELINE.read_text(encoding="utf-8").splitlines():
        if not raw or raw.startswith("#"):
            continue
        if "::" not in raw:
            continue
        rel, stripped = raw.split("::", 1)
        keys.add((rel, stripped))
    return keys


def write_baseline(hits: list[tuple[Path, int, str]]) -> None:
    header = [
        "# Baseline snapshot of pre-existing YYYY-MM-DD literals in tests/.",
        "# Generated by scripts/check_test_date_literals.py --update-baseline.",
        "# Format: <relative path>::<stripped line content>.",
        "# Each line listed here is grandfathered until its content changes.",
        "# Prefer fixing offenders (use a relative date or the # date-pinned-ok marker)",
        "# over expanding this baseline.",
        "",
    ]
    body = sorted({f"{p.relative_to(REPO_ROOT).as_posix()}::{line}" for p, _, line in hits})
    BASELINE.write_text("\n".join(header + body) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Rewrite the baseline file to grandfather every currently-unmarked literal. Use sparingly.",
    )
    args = parser.parse_args(argv)

    if not TESTS_DIR.exists():
        print(f"tests/ not found at {TESTS_DIR}; nothing to check.")
        return 0

    files = iter_test_files()
    hits = scan(files)

    if args.update_baseline:
        write_baseline(hits)
        print(f"Refreshed {BASELINE.relative_to(REPO_ROOT)} with {len(hits)} entries.")
        return 0

    baseline = load_baseline()
    new_violations = [
        (p, ln, s)
        for (p, ln, s) in hits
        if (p.relative_to(REPO_ROOT).as_posix(), s) not in baseline
    ]

    if not new_violations:
        print(
            f"OK — {len(hits)} grandfathered date literals, 0 new violations."
            if hits
            else "OK — no hardcoded date literals in tests/."
        )
        return 0

    print("Found hardcoded YYYY-MM-DD literals in tests/ that aren't grandfathered:")
    print()
    for path, lineno, snippet in new_violations:
        rel = path.relative_to(REPO_ROOT).as_posix()
        print(f"  {rel}:{lineno}: {snippet}")
    print()
    print(
        "Fix options:\n"
        "  1. Prefer a relative date — e.g. (date.today() - timedelta(days=7)).isoformat()\n"
        f"  2. If the date must be pinned, add `{OPT_OUT_MARKER}` to the end of the line.\n"
        "  3. To grandfather (rare): python scripts/check_test_date_literals.py --update-baseline"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
