from __future__ import annotations

import json
import sqlite3

import pytest

from universal_agent import task_hub
from universal_agent.tools import task_hub_bridge
from universal_agent.tools.task_hub_bridge import _task_hub_task_action_impl


def _connect(db_path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def _parse_tool_payload(result: dict) -> dict:
    content = result.get("content") or []
    assert content
    text = str(content[0].get("text") or "")
    assert not text.startswith("error:")
    return json.loads(text)


@pytest.mark.asyncio
async def test_task_hub_claim_alias_seizes_open_task(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)
        task_hub.upsert_item(
            conn,
            {
                "task_id": "email:claimable",
                "title": "Email task",
                "status": task_hub.TASK_STATUS_OPEN,
            },
        )

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await _task_hub_task_action_impl(
        {
            "task_id": "email:claimable",
            "action": "claim",
            "agent_id": "todo:test",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["action"] == "claim"
    assert payload["normalized_action"] == "seize"
    assert payload["item"]["status"] == task_hub.TASK_STATUS_IN_PROGRESS


@pytest.mark.asyncio
async def test_task_hub_claim_alias_is_idempotent_for_in_progress_task(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)
        task_hub.upsert_item(
            conn,
            {
                "task_id": "email:claimed",
                "title": "Email task",
                "status": task_hub.TASK_STATUS_IN_PROGRESS,
                "seizure_state": "seized",
            },
        )

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await _task_hub_task_action_impl(
        {
            "task_id": "email:claimed",
            "action": "claim",
            "agent_id": "todo:test",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["normalized_action"] == "seize"
    assert payload["already_claimed"] is True

    with _connect(db_path) as conn:
        assignments = conn.execute(
            "SELECT COUNT(*) AS c FROM task_hub_assignments WHERE task_id = ?",
            ("email:claimed",),
        ).fetchone()

    assert int(assignments["c"]) == 0


@pytest.mark.asyncio
async def test_task_hub_create(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await task_hub_bridge._task_hub_create_impl(
        {
            "title": "New proactive task",
            "description": "Generated by reflection",
            "priority": 2,
            "labels": ["proactive"],
            "source_kind": "reflection",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["task_id"] is not None
    assert payload["item"]["title"] == "New proactive task"
    assert payload["item"]["source_kind"] == "reflection"

    with _connect(db_path) as conn:
        item = task_hub.get_item(conn, payload["task_id"])
    assert item is not None
    assert item["title"] == "New proactive task"


@pytest.mark.asyncio
async def test_task_hub_promote_signals(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        from universal_agent import proactive_signals
        task_hub.ensure_schema(conn)
        proactive_signals.ensure_schema(conn)
        # Create a pending card
        conn.execute(
            """
            INSERT INTO proactive_signal_cards (
                card_id, source, card_type, title, summary, status, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            ("123", "test_source", "test_type", "Card 1", "Content", "pending", "2026-04-28T00:00:00Z", "2026-04-28T00:00:00Z"),
        )
        conn.commit()

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await task_hub_bridge._task_hub_promote_signals_impl(
        {
            "curated_cards": [
                {
                    "card_id": "123",
                    "task_title": "Promoted task 1",
                    "task_description": "Promoted description",
                    "priority": 3,
                    "rationale": "High value signal",
                }
            ]
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert len(payload["created_task_ids"]) == 1

    task_id = payload["created_task_ids"][0]
    with _connect(db_path) as conn:
        item = task_hub.get_item(conn, task_id)
        assert item is not None
        assert item["title"] == "Promoted task 1"
        assert item["metadata"]["source_card_id"] == "123"

        card = conn.execute(
            "SELECT status FROM proactive_signal_cards WHERE card_id = '123'"
        ).fetchone()
        assert card["status"] == "promoted"
