from __future__ import annotations

import json
import sqlite3

import pytest

from universal_agent import task_hub
from universal_agent.tools import task_hub_bridge
from universal_agent.tools.task_hub_bridge import _task_hub_task_action_impl


def _connect(db_path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def _parse_tool_payload(result: dict) -> dict:
    content = result.get("content") or []
    assert content
    text = str(content[0].get("text") or "")
    assert not text.startswith("error:")
    return json.loads(text)


@pytest.mark.asyncio
async def test_task_hub_claim_alias_seizes_open_task(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)
        task_hub.upsert_item(
            conn,
            {
                "task_id": "email:claimable",
                "title": "Email task",
                "status": task_hub.TASK_STATUS_OPEN,
            },
        )

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await _task_hub_task_action_impl(
        {
            "task_id": "email:claimable",
            "action": "claim",
            "agent_id": "todo:test",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["action"] == "claim"
    assert payload["normalized_action"] == "seize"
    assert payload["item"]["status"] == task_hub.TASK_STATUS_IN_PROGRESS


@pytest.mark.asyncio
async def test_task_hub_claim_alias_is_idempotent_for_in_progress_task(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)
        task_hub.upsert_item(
            conn,
            {
                "task_id": "email:claimed",
                "title": "Email task",
                "status": task_hub.TASK_STATUS_IN_PROGRESS,
                "seizure_state": "seized",
            },
        )

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await _task_hub_task_action_impl(
        {
            "task_id": "email:claimed",
            "action": "claim",
            "agent_id": "todo:test",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["normalized_action"] == "seize"
    assert payload["already_claimed"] is True

    with _connect(db_path) as conn:
        assignments = conn.execute(
            "SELECT COUNT(*) AS c FROM task_hub_assignments WHERE task_id = ?",
            ("email:claimed",),
        ).fetchone()

    assert int(assignments["c"]) == 0


@pytest.mark.asyncio
async def test_task_hub_create(monkeypatch, tmp_path):
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    result = await task_hub_bridge._task_hub_create_impl(
        {
            "title": "New proactive task",
            "description": "Generated by reflection",
            "priority": 2,
            "labels": ["proactive"],
            "source_kind": "reflection",
        }
    )
    payload = _parse_tool_payload(result)

    assert payload["success"] is True
    assert payload["task_id"] is not None
    assert payload["item"]["title"] == "New proactive task"
    assert payload["item"]["source_kind"] == "reflection"

    with _connect(db_path) as conn:
        item = task_hub.get_item(conn, payload["task_id"])
    assert item is not None
    assert item["title"] == "New proactive task"


@pytest.mark.asyncio
async def test_reflection_create_dedups_near_identical_titles(monkeypatch, tmp_path):
    """Two reflection creates with near-identical titles collapse to one task."""
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    first = _parse_tool_payload(
        await task_hub_bridge._task_hub_create_impl(
            {
                "title": "Investigate the HackerNews ingestion gap",
                "source_kind": "reflection",
            }
        )
    )
    # Differs only in casing, punctuation, and trailing whitespace.
    second = _parse_tool_payload(
        await task_hub_bridge._task_hub_create_impl(
            {
                "title": "  investigate the hackernews ingestion gap!!  ",
                "source_kind": "reflection",
            }
        )
    )

    assert first["task_id"] == second["task_id"]
    assert second.get("deduplicated") is True

    # Only one reflection row was actually inserted.
    with _connect(db_path) as conn:
        count = conn.execute(
            "SELECT COUNT(*) AS c FROM task_hub_items WHERE source_kind = 'reflection'"
        ).fetchone()
        first_row = task_hub.get_item(conn, first["task_id"])
    assert int(count["c"]) == 1
    assert first_row["incident_key"] == "reflection:investigate the hackernews ingestion gap"


@pytest.mark.asyncio
async def test_non_reflection_create_is_not_deduped(monkeypatch, tmp_path):
    """A non-reflection source_kind never collapses — distinct task_ids, no incident_key."""
    db_path = str(tmp_path / "activity_state.db")
    with _connect(db_path) as conn:
        task_hub.ensure_schema(conn)

    monkeypatch.setattr(task_hub_bridge, "get_activity_db_path", lambda: db_path)

    first = _parse_tool_payload(
        await task_hub_bridge._task_hub_create_impl(
            {"title": "Same proactive title", "source_kind": "proactive"}
        )
    )
    second = _parse_tool_payload(
        await task_hub_bridge._task_hub_create_impl(
            {"title": "Same proactive title", "source_kind": "proactive"}
        )
    )

    assert first["task_id"] != second["task_id"]
    assert first.get("deduplicated") is None
    assert second.get("deduplicated") is None

    with _connect(db_path) as conn:
        count = conn.execute(
            "SELECT COUNT(*) AS c FROM task_hub_items WHERE source_kind = 'proactive'"
        ).fetchone()
        row = task_hub.get_item(conn, first["task_id"])
    assert int(count["c"]) == 2
    assert row["incident_key"] is None
